name: Documentation Issue
description: Report a documentation issue or suggest and update
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete the sections below to provide a clear description of the issue or update you're suggesting.
  - type: textarea
    id: description
    attributes:
      label: Update Description
      placeholder: 'Example: "A Web Chat docs are out of date..."'
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: |
        Provide any additional context, background information, or links related to this update or issue.
  - type: checkboxes
    id: extra
    attributes:
      label: Extra checks
      options:
        - label: I have searched the existing issues related to documentation
          required: true
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion! We'll review the documentation and perform necessary updates.
