name: New Feature/Service Request
description: Suggest or request a new feature or service
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete the sections below to provide a clear description of the new feature or service you're suggesting.
        Please visit our [Discord server](https://discord.gg/5JMk8Z4) to discuss about new services.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      placeholder: 'Example: "A button on screen X that allows the user to do Y"'
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: |
        Provide any additional context, background information, or screenshots related to this feature request.
  - type: checkboxes
    id: extra
    attributes:
      label: Extra checks
      options:
        - label: This is NOT related to service based on another project
          required: true
        - label: I have checked the related repositories for existing feature request
          required: true
  - type: dropdown
    id: assign
    attributes:
      label: "Would you be interested in working on this feature?"
      options:
        - "Yes"
        - "No"
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion! We'll review it and explore the possibility of implementing this feature.
