name: Build Check
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - run: pip install mkdocs-material mkdocs-static-i18n

      - name: Build MkDocs site (strict)
        run: mkdocs build --strict
